spotify:
  CLIENT_ID: 'CLIENT_ID'
  CLIENT_SECRET: 'CLIENT_SECRET_ID'
  USER: 'USER_ID'
  REDIRECT_URL: 'http://localhost:8000/callback'
  SCOPE: 'playlist-modify-public playlist-modify-private'
  PLAYLIST: 'PLAYLIST_ID'
