spotify:
  CLIENT_ID: 'CLIENT_ID'
  CLIENT_SECRET: 'bCLIENT_SECRET'
  USER: 'USER'
  REDIRECT_URL: 'http://localhost:8000/callback'
  SCOPE: 'playlist-modify-public playlist-modify-private'
  PLAYLIST: 'PLAYLIST'
